### ISSUE TITLE
Single Navigation Bar

### ISSUE THREAD

**Issue by ggiande** [CSClubOfStanState/csclub-website#13]
- [ ] Determine if it's possible to create a navbar reusable component or if there's a way to make nav links dynamic.

**Comment by satyamraghuwanshi136** [comment]
Hey @ggiande, Yes there is a way to make a single navbar component and use it. I can work towards solving this issue.

**Comment by ggiande** [comment]
Hello @satyamraghuwanshi136 Feel free to fork the project, and work on a branch off of development. After you checked in your code, raise a or to development. Make sure to reference the issue number when raising the pull request. Please note to keep the project using basic html and css. The env doesn't allow for node :/

**Comment by satyamraghuwanshi136** [comment]
Hi @ggiande, I have solved this issue and made a PR. #18 

Thank you very much for letting me work on this issue.

**_let me know if I can help solve another issue. I will be happy to work._**
